In [52]:
!pip install --upgrade tensorflow

   ---------------------------------------- 0.0/331.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/331.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/331.9 MB 435.7 kB/s eta 0:12:42
   ---------------------------------------- 0.1/331.9 MB 1.2 MB/s eta 0:04:37
   ---------------------------------------- 0.2/331.9 MB 1.4 MB/s eta 0:03:59
   ---------------------------------------- 0.3/331.9 MB 1.3 MB/s eta 0:04:14
   ---------------------------------------- 0.4/331.9 MB 1.7 MB/s eta 0:03:18
   ---------------------------------------- 0.5/331.9 MB 1.6 MB/s eta 0:03:25
   ---------------------------------------- 0.6/331.9 MB 1.6 MB/s eta 0:03:31
   ---------------------------------------- 0.7/331.9 MB 1.8 MB/s eta 0:03:06
   ---------------------------------------- 0.9/331.9 MB 2.0 MB/s eta 0:02:47
   ---------------------------------------- 1.1/331.9 MB 2.2 MB/s eta 0:02:31
   ---------------------------------------- 1.4/331.9 MB 2.5 MB/s eta 0:02:1

  You can safely remove it manually.
  You can safely remove it manually.
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\Welcome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\tensorflow\\compiler\\mlir\\lite\\python\\_pywrap_converter_api.pyd'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
!pip install nltk

In [53]:
!pip install lightgbm sentence-transformers


   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
    --------------------------------------- 0.0/1.5 MB 325.1 kB/s eta 0:00:05
   -- ------------------------------------- 0.1/1.5 MB 651.6 kB/s eta 0:00:03
   ------- -------------------------------- 0.3/1.5 MB 1.7 MB/s eta 0:00:01
   -------------- ------------------------- 0.5/1.5 MB 2.4 MB/s eta 0:00:01
   ------------------- -------------------- 0.7/1.5 MB 2.6 MB/s eta 0:00:01
   ----------------------------- ---------- 1.1/1.5 MB 3.2 MB/s eta 0:00:01
   -------------------------------------- - 1.4/1.5 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 3.7 MB/s eta 0:00:00



[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
!pip install accelerate -U

In [ ]:
!pip install scikit-learn

In [ ]:
!pip install -U sentence-transformers


# BTL Question Classification

## Dataset Initializaiton

In [48]:
import pandas as pd
train_df = pd.read_csv('train_df.csv')
test_df = pd.read_csv('test_df.csv')

SyntaxError: invalid syntax (419723173.py, line 3)

In [50]:

print(train_df['BTL '].value_counts())

BTL 
1    171
6    160
5    149
3    138
4    119
2     86
Name: count, dtype: int64


In [6]:
print(len(train_df))
print(len(test_df))

823
206


In [45]:
from sentence_transformers import SentenceTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import pandas as pd

# Load your train/test data
X_train = train_df['QUESTION'].tolist()
y_train = train_df['BTL '].tolist()

X_test = test_df['QUESTION'].tolist()
y_test = test_df['BTL '].tolist()

# Load lightweight SentenceTransformer model
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

# Get embeddings
X_train_emb = model.encode(X_train, batch_size=32, show_progress_bar=True)
X_test_emb = model.encode(X_test, batch_size=32, show_progress_bar=True)

# Train classifier
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train_emb, y_train)

# Predict & evaluate
y_pred = clf.predict(X_test_emb)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


c:\Users\Welcome\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\Welcome\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:157: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Welcome\.cache\huggingface\hub\models--sentence-transformers--paraphrase-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer 

Accuracy: 0.6504854368932039

Classification Report:
               precision    recall  f1-score   support

           1       0.74      0.65      0.69        43
           2       0.71      0.55      0.62        22
           3       0.44      0.42      0.43        38
           4       0.72      0.67      0.69        39
           5       0.51      0.65      0.57        31
           6       0.80      0.97      0.88        33

    accuracy                           0.65       206
   macro avg       0.65      0.65      0.65       206
weighted avg       0.65      0.65      0.65       206



In [55]:
from sentence_transformers import SentenceTransformer
from lightgbm import LGBMClassifier

model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')  # smaller and better than paraphrase-MiniLM

X_train = model.encode(train_df['QUESTION'].tolist(), show_progress_bar=True)
y_train = train_df['BTL '].tolist()

X_test = model.encode(test_df['QUESTION'].tolist(), show_progress_bar=True)
y_test = test_df['BTL '].tolist()

clf = LGBMClassifier(n_estimators=200)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))


Batches: 100%|██████████| 7/7 [00:02<00:00,  2.51it/s]


[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.005911 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 97920
[LightGBM] [Info] Number of data points in the train set: 823, number of used features: 384
[LightGBM] [Info] Start training from score -1.571293
[LightGBM] [Info] Start training from score -2.258609
[LightGBM] [Info] Start training from score -1.785703
[LightGBM] [Info] Start training from score -1.933833
[LightGBM] [Info] Start training from score -1.709010
[LightGBM] [Info] Start training from score -1.637782
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [

c:\Users\Welcome\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


## SVM

In [2]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score
from sklearn.pipeline import make_pipeline

In [56]:

vectorizer = TfidfVectorizer(
    ngram_range=(1, 3),              # Unigram to Trigram
    stop_words='english',
    max_features=20000,
    sublinear_tf=True,               # log scale term frequency
    norm='l2'                        # normalize vectors
)
svm_model = SVC(kernel='linear', random_state=42)

pipeline = make_pipeline(vectorizer, svm_model)

pipeline.fit(train_df['QUESTION'], train_df['BTL '])

predictions = pipeline.predict(test_df['QUESTION'])

print("Accuracy:", accuracy_score(test_df['BTL '], predictions))
print("\nClassification Report:\n", classification_report(test_df['BTL '], predictions))


Accuracy: 0.7572815533980582

Classification Report:
               precision    recall  f1-score   support

           1       0.67      0.91      0.77        43
           2       0.80      0.55      0.65        22
           3       0.75      0.55      0.64        38
           4       0.86      0.77      0.81        39
           5       0.76      0.71      0.73        31
           6       0.78      0.97      0.86        33

    accuracy                           0.76       206
   macro avg       0.77      0.74      0.74       206
weighted avg       0.77      0.76      0.75       206



In [57]:
import joblib
joblib.dump(pipeline, "btl_model.pkl")


['btl_model.pkl']

In [40]:
from sklearn.ensemble import RandomForestClassifier

pipeline = make_pipeline(
    TfidfVectorizer(ngram_range=(1, 2), stop_words='english'),
    RandomForestClassifier(n_estimators=200, random_state=42)
)


pipeline.fit(train_df['QUESTION'], train_df['BTL '])

predictions = pipeline.predict(test_df['QUESTION'])

print("Accuracy:", accuracy_score(test_df['BTL '], predictions))
print("\nClassification Report:\n", classification_report(test_df['BTL '], predictions))

Accuracy: 0.6796116504854369

Classification Report:
               precision    recall  f1-score   support

           1       0.52      0.93      0.67        43
           2       0.57      0.55      0.56        22
           3       0.56      0.26      0.36        38
           4       0.82      0.69      0.75        39
           5       0.90      0.61      0.73        31
           6       0.89      0.97      0.93        33

    accuracy                           0.68       206
   macro avg       0.71      0.67      0.67       206
weighted avg       0.71      0.68      0.67       206



## BERT

In [9]:
!pip install transformers datasets torch


[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import torch
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from sklearn.model_selection import train_test_split
from datasets import load_dataset, Dataset
from transformers import DataCollatorWithPadding

c:\Users\Welcome\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
# Convert to Hugging Face Dataset format
train_dataset = load_dataset('csv', data_files='train_df.csv')
test_dataset = load_dataset('csv', data_files='test_df.csv')

train_dataset = train_dataset['train']
test_dataset = test_dataset['train']

In [3]:
model_name = "bert-base-uncased"
tokenizer = BertTokenizer.from_pretrained(model_name)

# Tokenize the data
def tokenize_function(examples):
    return tokenizer(examples['QUESTION'], padding="max_length", truncation=True)

train_dataset = train_dataset.map(tokenize_function, batched=True)
test_dataset = test_dataset.map(tokenize_function, batched=True)

# Set format to torch
train_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'BTL '])
test_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'BTL '])


In [4]:
num_labels = 6  # For BTL levels 1 to 6
model = BertForSequenceClassification.from_pretrained(model_name, num_labels=num_labels)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [5]:
training_args = TrainingArguments(
    output_dir='./results',
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)


c:\Users\Welcome\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\training_args.py:1474: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(


In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    tokenizer=tokenizer,
    data_collator=data_collator
)

trainer.train()

In [ ]:
results = trainer.evaluate()
print(results)

In [ ]:
def predict_btl(question):
    inputs = tokenizer(question, return_tensors="pt", padding=True, truncation=True, max_length=128)
    outputs = model(**inputs)
    predicted_label = torch.argmax(outputs.logits, dim=1).item() + 1  # Adding 1 to match BTL range 1-6
    return predicted_label

# Example
question = "What is the time complexity of quicksort?"
predicted_btl = predict_btl(question)
print(f"Predicted BTL Level: {predicted_btl}")


# Difficulty Prediction Model

## Data Processing

In [2]:
import pandas as pd
train_df = pd.read_csv('dataset/train_df.csv')
test_df = pd.read_csv('dataset/test_df.csv')

print(train_df['BTL '].value_counts())

BTL 
1    171
6    160
5    149
3    138
4    119
2     86
Name: count, dtype: int64


In [ ]:
difficulty_df = pd.DataFrame()

for btl in train_df['BTL '].unique():
    btl_df = train_df[train_df['BTL '] == btl]
    
    sampled = btl_df.sample(n=min(80, len(btl_df)), random_state=42)
    
    difficulty_df = pd.concat([difficulty_df, sampled], ignore_index=True)

difficulty_df.to_csv('dataset/difficulty_df.csv', index=False)

print("Saved sampled difficulty_df.csv with", len(difficulty_df), "rows")

Saved sampled difficulty_df.csv with 480 rows


In [ ]:
print(train_df['BTL '].value_counts())

In [ ]:
import pandas as pd
import random

df = pd.read_csv('dataset/difficulty_df.csv')

topics = ['Arrays', 'Recursion', 'Sorting', 'Linked List', 'Trees', 'Other']

topic_choices = topics[:-1] + ['Other']*1  # makes 'Other' less frequent
df['topic'] = [random.choice(topic_choices) for _ in range(len(df))]

# Assign difficulty randomly (1 = easy, 2 = medium, 3 = hard)
df['difficulty'] = [random.randint(1, 3) for _ in range(len(df))]

# Save the updated CSV
df.to_csv('dataset/difficulty_df_updated.csv', index=False)

print("Updated CSV saved as difficulty_df_updated.csv")


Updated CSV saved as difficulty_df_updated.csv


## Classifier

In [53]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.optimizers import Adam
import random
import json
from tensorflow.keras import layers, models


In [54]:
prefs_list = []
#User difficulty rating across each of the BTL 
for _ in range(10):
    prefs = {
        'remembering': random.randint(1, 5),
        'understanding': random.randint(1, 5),
        'applying': random.randint(1, 5),
        'analyzing': random.randint(1, 5),
        'evaluating': random.randint(1, 5),
        'creating': random.randint(1, 5)
    }
    prefs_list.append(prefs)

for p in prefs_list:
    print(p)


{'remembering': 4, 'understanding': 3, 'applying': 4, 'analyzing': 5, 'evaluating': 4, 'creating': 1}
{'remembering': 2, 'understanding': 1, 'applying': 5, 'analyzing': 4, 'evaluating': 1, 'creating': 5}
{'remembering': 3, 'understanding': 1, 'applying': 4, 'analyzing': 2, 'evaluating': 3, 'creating': 4}
{'remembering': 3, 'understanding': 3, 'applying': 5, 'analyzing': 1, 'evaluating': 2, 'creating': 4}
{'remembering': 4, 'understanding': 3, 'applying': 1, 'analyzing': 2, 'evaluating': 2, 'creating': 2}
{'remembering': 3, 'understanding': 3, 'applying': 5, 'analyzing': 5, 'evaluating': 3, 'creating': 5}
{'remembering': 1, 'understanding': 3, 'applying': 4, 'analyzing': 3, 'evaluating': 2, 'creating': 3}
{'remembering': 3, 'understanding': 4, 'applying': 1, 'analyzing': 2, 'evaluating': 2, 'creating': 5}
{'remembering': 3, 'understanding': 1, 'applying': 3, 'analyzing': 3, 'evaluating': 5, 'creating': 2}
{'remembering': 1, 'understanding': 5, 'applying': 1, 'analyzing': 4, 'evaluating'

In [55]:
# Convert to array
pref_vecs = np.array([
    [p["remembering"], p["understanding"], p["applying"],
     p["analyzing"], p["evaluating"], p["creating"]]
    for p in prefs_list
], dtype=np.float32)

print(pref_vecs.shape)  # shape
for pv in pref_vecs:
    print(pv)    


(10, 6)
[4. 3. 4. 5. 4. 1.]
[2. 1. 5. 4. 1. 5.]
[3. 1. 4. 2. 3. 4.]
[3. 3. 5. 1. 2. 4.]
[4. 3. 1. 2. 2. 2.]
[3. 3. 5. 5. 3. 5.]
[1. 3. 4. 3. 2. 3.]
[3. 4. 1. 2. 2. 5.]
[3. 1. 3. 3. 5. 2.]
[1. 5. 1. 4. 1. 3.]


In [56]:
LIBRARY_FILE = "library.json"
with open(LIBRARY_FILE, "r", encoding="utf-8") as f:
    QUESTIONS = json.load(f)["questions"]

In [57]:
len(QUESTIONS)

77

In [58]:
print(QUESTIONS[0])

{'q_id': 'q_1', 'topic': 'Balanced Search Tree', 'question': 'What is a balanced search tree and how does it differ from a binary search tree?', 'options': ['A balanced search tree maintains minimal height for efficient operations, while a binary search tree does not guarantee balance', 'Both are the same', 'A balanced search tree stores only even numbers', 'A binary search tree is always balanced'], 'correct_option_index': 0, 'predicted_btl': 1, 'difficulty': '2'}


In [59]:
#topic, difficulty concatenated with question
texts = [f"{q['topic']} {q['question']} difficulty: {q['difficulty']} BTL: {q['predicted_btl']}" for q in QUESTIONS]
print("text: ",texts[0])

#vectorize
vectorizer = TfidfVectorizer(max_features=500)
X_text = vectorizer.fit_transform(texts).toarray()
print("text encoded: ", X_text[0])


text:  Balanced Search Tree What is a balanced search tree and how does it differ from a binary search tree? difficulty: 2 BTL: 1
text encoded:  [0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.09731341 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.4527771  0.         0.         0.
 0.         0.         0.         0.         0.         0.16797906
 0.         0.         0.         0.         0.         0.05316661
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0

In [60]:
# X_text_repeated = np.repeat(X_text, repeats=len(prefs_list), axis=0)  
# pref_vecs_repeated = np.tile(pref_vecs, (len(QUESTIONS), 1))

# # Combine them
# X = np.hstack([X_text_repeated, pref_vecs_repeated])

import itertools
cartesian_product = [np.concatenate((p, x)) for p, x in itertools.product(pref_vecs, X_text)]
X = np.array(cartesian_product, dtype=np.float32)

In [61]:
print(len(X))
print(X.shape)
print(type(X))

770
(770, 445)
<class 'numpy.ndarray'>


In [30]:
print("combined input: ",X[0])

combined input:  [3.         1.         3.         5.         2.         2.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.09731341 0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.4527771  0.         0.         0.
 0.         0.         0.         0.         0.         0.16797906
 0.         0.         0.         0.         0.         0.05316661
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         

In [31]:
print("Training shape:", X.shape)

Training shape: (770, 445)


## VAE

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, Model
import keras.saving

# Parameters
input_dim = X.shape[1]
latent_dim = 64

# Encoder
inputs = layers.Input(shape=(input_dim,))
h = layers.Dense(128, activation="relu")(inputs)
z_mean = layers.Dense(latent_dim, name="z_mean")(h)
z_log_var = layers.Dense(latent_dim, name="z_log_var")(h)

def sampling(args):
    z_mean, z_log_var = args
    epsilon = tf.random.normal(shape=tf.shape(z_mean))
    return z_mean + tf.exp(0.5 * z_log_var) * epsilon

z = layers.Lambda(sampling, name="z")([z_mean, z_log_var])

encoder = Model(inputs, [z_mean, z_log_var, z], name="encoder")

# Decoder
latent_inputs = layers.Input(shape=(latent_dim,))
h_decoded = layers.Dense(128, activation="relu")(latent_inputs)
outputs = layers.Dense(input_dim, activation="sigmoid")(h_decoded)

decoder = Model(latent_inputs, outputs, name="decoder")

# VAE model
outputs = decoder(encoder(inputs)[2])
vae = Model(inputs, outputs, name="vae")

# Custom training loop for VAE
@keras.saving.register_keras_serializable()
class VAE(Model):
    def __init__(self, encoder, decoder, **kwargs):
        super(VAE, self).__init__(**kwargs)
        self.encoder = encoder
        self.decoder = decoder
        self.total_loss_tracker = tf.keras.metrics.Mean(name="loss")
        self.reconstruction_loss_tracker = tf.keras.metrics.Mean(name="reconstruction_loss")
        self.kl_loss_tracker = tf.keras.metrics.Mean(name="kl_loss")

    def train_step(self, data):
        if isinstance(data, tuple):  
            data = data[0]

        with tf.GradientTape() as tape:
            z_mean, z_log_var, z = self.encoder(data)
            reconstruction = self.decoder(z)
            reconstruction_loss = tf.reduce_mean(
                tf.reduce_sum(tf.square(data - reconstruction), axis=1)
            )
            kl_loss = -0.5 * tf.reduce_mean(
                tf.reduce_sum(1 + z_log_var - tf.square(z_mean) - tf.exp(z_log_var), axis=1)
            )
            total_loss = reconstruction_loss + kl_loss

        grads = tape.gradient(total_loss, self.trainable_weights)
        self.optimizer.apply_gradients(zip(grads, self.trainable_weights))

        self.total_loss_tracker.update_state(total_loss)
        self.reconstruction_loss_tracker.update_state(reconstruction_loss)
        self.kl_loss_tracker.update_state(kl_loss)

        return {
            "loss": self.total_loss_tracker.result(),
            "reconstruction_loss": self.reconstruction_loss_tracker.result(),
            "kl_loss": self.kl_loss_tracker.result(),
        }

# Compile & Train
vae = VAE(encoder, decoder)
vae.compile(optimizer="adam")


In [64]:
vae.fit(X, epochs=20, batch_size=32)

Epoch 1/20


25/25 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - kl_loss: 4.2516 - loss: 132.4323 - reconstruction_loss: 128.1807
Epoch 2/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - kl_loss: 10.3421 - loss: 49.1935 - reconstruction_loss: 38.8513
Epoch 3/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - kl_loss: 3.5473 - loss: 41.1106 - reconstruction_loss: 37.5633
Epoch 4/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - kl_loss: 3.1038 - loss: 38.7706 - reconstruction_loss: 35.6667
Epoch 5/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - kl_loss: 2.4006 - loss: 38.5235 - reconstruction_loss: 36.1229
Epoch 6/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - kl_loss: 1.9687 - loss: 38.2280 - reconstruction_loss: 36.2593
Epoch 7/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - kl_loss: 1.9804 - loss: 37.8374 - reconstruction_loss: 35.8570
Epoch 8/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - kl_loss: 1.6426 - loss: 37.3804 - reconstruction_loss: 35.7378
Epoch 9/20
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - kl_loss: 1.4418 - loss: 37.5198 - re

In [65]:
# Save the full VAE model
#vae.save("vae_model.keras")

# Also save encoder and decoder separately if you defined them
encoder.save("vae_encoder.keras")
decoder.save("vae_decoder.keras")


In [68]:
from tensorflow import keras
import numpy as np
import keras

testprefs = {"remembering": 4, "understanding": 3, "applying": 2,
             "analyzing": 2, "evaluating": 1, "creating": 3}


@keras.saving.register_keras_serializable()
def sampling(args):
    z_mean, z_log_var = args
    batch = tf.shape(z_mean)[0]
    dim = tf.shape(z_mean)[1]
    epsilon = tf.random.normal(shape=(batch, dim))
    return z_mean + tf.exp(0.5 * z_log_var) * epsilon

encoder = keras.models.load_model(
    "vae_encoder.keras",
    custom_objects={"sampling": sampling}
)
decoder = keras.models.load_model("vae_decoder.keras")

difficulties = []
pref_vec = np.array([[testprefs["remembering"], testprefs["understanding"], 
                      testprefs["applying"], testprefs["analyzing"], 
                      testprefs["evaluating"], testprefs["creating"]]], dtype=np.float32)

for q in QUESTIONS:
    text = f"{q['topic']} {q['question']} difficulty: {q['difficulty']} 'BTL:' {q['predicted_btl']}"
    vec = vectorizer.transform([text]).toarray()
    x = np.hstack([vec, pref_vec])

    # Encode → Decode
    # Correct usage
    z_mean, z_log_var, z = encoder.predict(x, verbose=0)

# Feed only z to the decoder
    recon = decoder.predict(z, verbose=0)

    err = np.mean(np.square(x - recon))
    difficulties.append((q, err))


In [75]:
# thresholding
threshold = np.median([e for (_, e) in difficulties])
filtered_questions = [q for q, e in difficulties if e <= threshold]

In [76]:
for q, score in difficulties:
    print(f"QID: {q['q_id']}, Predicted Wrong Score: {score:.4f}")

QID: q_5_12, Predicted Wrong Score: 0.1093
QID: 555, Predicted Wrong Score: 0.1096
QID: 713, Predicted Wrong Score: 0.1100
QID: 758, Predicted Wrong Score: 0.1103
QID: q_274, Predicted Wrong Score: 0.1103
QID: 992, Predicted Wrong Score: 0.1104
QID: q_5_4, Predicted Wrong Score: 0.1107
QID: q_291, Predicted Wrong Score: 0.1107
QID: 1133, Predicted Wrong Score: 0.1108
QID: 521, Predicted Wrong Score: 0.1109
QID: q_5_8, Predicted Wrong Score: 0.1109
QID: 533, Predicted Wrong Score: 0.1109
QID: 452, Predicted Wrong Score: 0.1109
QID: 996, Predicted Wrong Score: 0.1110
QID: 1030, Predicted Wrong Score: 0.1110
QID: 546, Predicted Wrong Score: 0.1110
QID: q_5, Predicted Wrong Score: 0.1113
QID: q_2, Predicted Wrong Score: 0.1114
QID: 633, Predicted Wrong Score: 0.1114
QID: q_5_13, Predicted Wrong Score: 0.1115
QID: 703, Predicted Wrong Score: 0.1115
QID: 1104, Predicted Wrong Score: 0.1115
QID: 687, Predicted Wrong Score: 0.1116
QID: q_5_17, Predicted Wrong Score: 0.1116
QID: q_5_16, Predict

In [73]:
# Sort by predicted "wrongness"
difficulties.sort(key=lambda x: x[1], reverse=True)
for d in difficulties[:10]:  # Top 10 most difficult
    print(f"QID: {d[0]['q_id']}, Question: {d[0]['question']} ,Predicted Wrong Score: {d[1]:.4f}")

QID: 998, Question: Why would industries implement edge computing in remote environments? ,Predicted Wrong Score: 0.1123
QID: q_5_5, Question: What are the trade-offs between using an explicit "previous" pointer and a "reverse" pointer when reversing a doubly linked list? ,Predicted Wrong Score: 0.1123
QID: 614, Question: Compare and contrast different methods for secure authentication in wireless communication systems and analyze their vulnerabilities. ,Predicted Wrong Score: 0.1123
QID: 584, Question: Evaluate the effectiveness of using machine learning algorithms for detecting and preventing cyberattacks in real-time. ,Predicted Wrong Score: 0.1123
QID: 699, Question: Evaluate the effectiveness of various authentication methods (OAuth, JWT, API keys) in securing IoT devices. ,Predicted Wrong Score: 0.1123
QID: 500, Question: How do I concatenate two lists? ,Predicted Wrong Score: 0.1123
QID: 634, Question: Write a program in Python to produce a star triangle. ,Predicted Wrong Score:

In [74]:
# Top 10 easiest questions (lowest reconstruction error)
difficulties.sort(key=lambda x: x[1], reverse=False)
for d in difficulties[:10]:  
    print(f"QID: {d[0]['q_id']}, Question: {d[0]['question']} ,Predicted Wrong Score: {d[1]:.4f}")


QID: q_5_12, Question: Assess the efficiency of a blockchain-based smart contract platform for automating business processes and transactions. ,Predicted Wrong Score: 0.1093
QID: 555, Question: Propose innovative solutions for securing wireless networks against advanced persistent threats and evaluate their effectiveness. ,Predicted Wrong Score: 0.1096
QID: 713, Question: Compare the advantages and limitations of TCP versus UDP for network communications. ,Predicted Wrong Score: 0.1100
QID: 758, Question: Compare the advantages of using Scrum versus Kanban frameworks in managing software projects. ,Predicted Wrong Score: 0.1103
QID: q_274, Question: Does Python make use of access specifiers? ,Predicted Wrong Score: 0.1103
QID: 992, Question: How can AI and robotics improve warehouse management processes? ,Predicted Wrong Score: 0.1104
QID: q_5_4, Question: Judge the effectiveness of a machine learning model for sentiment analysis based on its accuracy and generalization performance. ,P

## AutoEncoder

In [11]:
#Autoencoder
input_dim = X.shape[1] 
encoding_dim = 64 #bottleneck size

input_layer = layers.Input(shape=(input_dim,))
encoded = layers.Dense(encoding_dim, activation="relu")(input_layer) #encoder
decoded = layers.Dense(input_dim, activation="sigmoid")(encoded) #decoder

autoencoder = models.Model(input_layer, decoded)
autoencoder.compile(optimizer="adam", loss="mse")

In [12]:
autoencoder.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 445)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │        28,544 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 445)            │        28,925 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 57,469 (224.49 KB)

 Trainable params: 57,469 (224.49 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
#TRAIN
autoencoder.fit(X, X, epochs=100, batch_size=1, verbose=0)
encoder = models.Model(input_layer, encoded)

In [ ]:
import joblib

# After training autoencoder
autoencoder.save("autoencoder_model.h5")
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

In [ ]:
from tensorflow.keras.models import load_model
import joblib

autoencoder = load_model("autoencoder_model.h5", compile = False)
vectorizer = joblib.load("tfidf_vectorizer.pkl")

difficulties = []
testprefs = {"remembering": 4, "understanding": 3, "applying": 2,
             "analyzing": 2, "evaluating": 1, "creating": 3}
pref_vec = np.array([[testprefs["remembering"], testprefs["understanding"], testprefs["applying"],
                      testprefs["analyzing"], testprefs["evaluating"], testprefs["creating"]]], dtype=np.float32)

#TEST and RETRIEVE MSE 
for q in QUESTIONS:
    text = f"{q['topic']} {q['question']} difficulty: {q['difficulty']} 'BTL:' {q['predicted_btl']}"
    vec = vectorizer.transform([text]).toarray()
    
    x = np.hstack([vec, pref_vec])

    recon = autoencoder.predict(x, verbose=0)
    err = np.mean(np.square(x - recon))
    difficulties.append((q, err))

In [69]:
# thresholding
threshold = np.median([e for (_, e) in difficulties])
filtered_questions = [q for q, e in difficulties if e <= threshold]

In [71]:
for q, score in difficulties:
    print(f"QID: {q['q_id']}, Predicted Wrong Score: {score:.4f}")

QID: q_1, Predicted Wrong Score: 0.1120
QID: q_2, Predicted Wrong Score: 0.1114
QID: q_3, Predicted Wrong Score: 0.1122
QID: q_4, Predicted Wrong Score: 0.1118
QID: q_5, Predicted Wrong Score: 0.1113
QID: q_274, Predicted Wrong Score: 0.1103
QID: q_281, Predicted Wrong Score: 0.1120
QID: q_284, Predicted Wrong Score: 0.1120
QID: q_287, Predicted Wrong Score: 0.1122
QID: q_291, Predicted Wrong Score: 0.1107
QID: q_309, Predicted Wrong Score: 0.1117
QID: 500, Predicted Wrong Score: 0.1123
QID: 506, Predicted Wrong Score: 0.1119
QID: 422, Predicted Wrong Score: 0.1116
QID: 554, Predicted Wrong Score: 0.1122
QID: 521, Predicted Wrong Score: 0.1109
QID: 556, Predicted Wrong Score: 0.1122
QID: 452, Predicted Wrong Score: 0.1109
QID: 467, Predicted Wrong Score: 0.1123
QID: 413, Predicted Wrong Score: 0.1122
QID: 546, Predicted Wrong Score: 0.1110
QID: 402, Predicted Wrong Score: 0.1122
QID: 533, Predicted Wrong Score: 0.1109
QID: 543, Predicted Wrong Score: 0.1123
QID: 530, Predicted Wrong Sc

In [23]:
# Sort by predicted "wrongness"
difficulties.sort(key=lambda x: x[1], reverse=True)
for d in difficulties[:10]:  # Top 10 most difficult
    print(f"QID: {d[0]['q_id']}, Question: {d[0]['question']} ,Predicted Wrong Score: {d[1]:.4f}")

QID: 991, Question: How can blockchain be applied to supply chain management? ,Predicted Wrong Score: 0.1081
QID: 506, Question: Could you compare and contrast the time complexity of binary search in a sorted array with that in a binary search tree? ,Predicted Wrong Score: 0.1069
QID: 703, Question: Analyze the effectiveness of containerization (Docker) versus virtualization (VMware) for cloud application management. ,Predicted Wrong Score: 0.1063
QID: q_5_16, Question: What is inheritance in Python, and how does it facilitate code reuse and organization? ,Predicted Wrong Score: 0.1062
QID: 543, Question: Analyze the impact of algorithmic bias on the fairness and inclusivity of machine learning models in hiring practices. ,Predicted Wrong Score: 0.1062
QID: q_5_15, Question: Can you provide examples of algorithms or strategies for converting a sorted array into a balanced binary search tree? ,Predicted Wrong Score: 0.1062
QID: 402, Question: Critically analyze the challenges and benefi

In [25]:
# Top 10 easiest questions (lowest reconstruction error)
difficulties.sort(key=lambda x: x[1], reverse=False)
for d in difficulties[:10]:  
    print(f"QID: {d[0]['q_id']}, Question: {d[0]['question']} ,Predicted Wrong Score: {d[1]:.4f}")


QID: 992, Question: How can AI and robotics improve warehouse management processes? ,Predicted Wrong Score: 0.1005
QID: 555, Question: Propose innovative solutions for securing wireless networks against advanced persistent threats and evaluate their effectiveness. ,Predicted Wrong Score: 0.1005
QID: q_274, Question: Does Python make use of access specifiers? ,Predicted Wrong Score: 0.1010
QID: 500, Question: How do I concatenate two lists? ,Predicted Wrong Score: 0.1012
QID: 994, Question: What is the primary goal of automatically classifying and prioritizing cybersecurity incidents? ,Predicted Wrong Score: 0.1012
QID: 1013, Question: Which is the main objective of optimizing database indexing in distributed systems? ,Predicted Wrong Score: 0.1018
QID: 758, Question: Compare the advantages of using Scrum versus Kanban frameworks in managing software projects. ,Predicted Wrong Score: 0.1019
QID: 1129, Question: Which of the following best describes a decentralized application (dApp)? ,P